sudo: false
dist: trusty

addons:
  chrome: stable

language: ruby
rvm:
  - 2.5.1

before_script:
  # set up xvfb and give it some time to start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 1; done"
